backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/header__background/header__background.md"
        fields:
          - label: "Featured Image"
            name: "thumbnail"
            widget: "image"
      - label: "Card"
        name: "card"
        file: "content/Card/Card.md"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - label: "Featured Image"
            name: "thumbnail"
            widget: "image"
          - label: "Featured Image"
            name: "background"
            widget: "image"
      - label: "Description"
        name: "description"
        file: "content/Description/Description.md"
        fields:
          - { label: "Description", name: "description", widget: "text" }
      - label: "Education"
        name: "education"
        file: "content/Education/Education.md"
        fields:
          - { label: "Title1", name: "title1", widget: "string" }
          - { label: "Description1", name: "description1", widget: "text" }
          - { label: "Date1", name: "date1", widget: "text" }
          - { label: "Content1", name: "content1", widget: "text" }

          - { label: "Title2", name: "title2", widget: "string" }
          - { label: "Description2", name: "description2", widget: "text" }
          - { label: "Date2", name: "date2", widget: "text" }
          - { label: "Content2", name: "content2", widget: "text" }

          - { label: "Title3", name: "title3", widget: "string" }
          - { label: "Description3", name: "description3", widget: "text" }
          - { label: "Date3", name: "date3", widget: "text" }
          - { label: "Content3", name: "content3", widget: "text" }

          - { label: "Title4", name: "title4", widget: "string" }
          - { label: "Description4", name: "description4", widget: "text" }
          - { label: "Date4", name: "date4", widget: "text" }
          - { label: "Content4", name: "content4", widget: "text" }

          - { label: "Title5", name: "title5", widget: "string" }
          - { label: "Description5", name: "description5", widget: "text" }
          - { label: "Date5", name: "date5", widget: "text" }
          - { label: "Content5", name: "content5", widget: "text" }

          - { label: "Title6", name: "title6", widget: "string" }
          - { label: "Description6", name: "description6", widget: "text" }
          - { label: "Date6", name: "date6", widget: "text" }
          - { label: "Content6", name: "content6", widget: "text" }
