backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/Home.md"
        fields:
          - label: "Card"
            name: "card"
            widget: "object"
            collapsed: true
            fields:
              - label: "Your Name"
                name: "yourName"
                widget: "string"

              - label: "Your Job"
                name: "yourJob"
                widget: "string"

              - label: "Avatar"
                name: "avtCard"
                widget: "image"
          - label: "Banner"
            name: "banner"
            widget: "object"
            collapsed: true
            fields:
              - label: "Avatar Menu"
                name: "avatar"
                widget: "image"

              - label: "Header Background"
                name: "bg"
                widget: "image"
