backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Card"
        name: "card"
        file: "content/Card/Card.md"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - label: "Featured Image"
            name: "thumbnail"
            widget: "image"
          - label: "Featured Image"
            name: "background"
            widget: "image"
      - label: "Description"
        name: "description"
        file: "content/Description/Description.md"
        fields:
          - { label: "Description", name: "description", widget: "text" }
      - label: "Education"
        name: "education"
        file: "content/Education/Education.md"
        fields:
          - { label: "Title1", name: "title1", widget: "string" }
          - { label: "Description1", name: "description1", widget: "text" }
          - { label: "Date1", name: "date1", widget: "text" }
          - { label: "Content1", name: "content1", widget: "text" }

          - { label: "Title2", name: "title2", widget: "string" }
          - { label: "Description2", name: "description2", widget: "text" }
          - { label: "Date2", name: "date2", widget: "text" }
          - { label: "Content2", name: "content2", widget: "text" }

          - { label: "Title3", name: "title3", widget: "string" }
          - { label: "Description3", name: "description3", widget: "text" }
          - { label: "Date3", name: "date3", widget: "text" }
          - { label: "Content3", name: "content3", widget: "text" }

          - { label: "Title4", name: "title4", widget: "string" }
          - { label: "Description4", name: "description4", widget: "text" }
          - { label: "Date4", name: "date4", widget: "text" }
          - { label: "Content4", name: "content4", widget: "text" }

          - { label: "Title5", name: "title5", widget: "string" }
          - { label: "Description5", name: "description5", widget: "text" }
          - { label: "Date5", name: "date5", widget: "text" }
          - { label: "Content5", name: "content5", widget: "text" }

          - { label: "Title6", name: "title6", widget: "string" }
          - { label: "Description6", name: "description6", widget: "text" }
          - { label: "Date6", name: "date6", widget: "text" }
          - { label: "Content6", name: "content6", widget: "text" }
      - label: skills
        name: skills
        file: "content/Skills/Skills.md"
        fields:
          - { label: "FirstSkill", name: "professional", widget: "string" }
          - { label: "language1", name: "pro1", widget: "string" }
          - { label: "Percent1", name: "proPercent1", widget: "number" }
          - { label: "language2", name: "pro2", widget: "string" }
          - { label: "Percent2", name: "proPercent2", widget: "number" }
          - { label: "language3", name: "pro3", widget: "string" }
          - { label: "Percent3", name: "proPercent3", widget: "number" }
          - { label: "language4", name: "pro4", widget: "string" }
          - { label: "Percent4", name: "proPercent4", widget: "number" }

          - { label: "SecondSkill", name: "personal", widget: "string" }
          - { label: "language1", name: "per1", widget: "string" }
          - { label: "Percent1", name: "perPercent1", widget: "number" }
          - { label: "language2", name: "per2", widget: "string" }
          - { label: "Percent2", name: "perPercent2", widget: "number" }
          - { label: "language3", name: "per3", widget: "string" }
          - { label: "Percent3", name: "perPercent3", widget: "number" }
          - { label: "language4", name: "per4", widget: "string" }
          - { label: "Percent4", name: "perPercent4", widget: "number" }

          - { label: "ThirdSkill", name: "software", widget: "string" }
          - { label: "language1", name: "sof1", widget: "string" }
          - { label: "Percent1", name: "sofPercent1", widget: "number" }
          - { label: "language2", name: "sof2", widget: "string" }
          - { label: "Percent2", name: "sofPercent2", widget: "number" }
          - { label: "language3", name: "sof3", widget: "string" }
          - { label: "Percent3", name: "sofPercent3", widget: "number" }
          - { label: "language4", name: "sof4", widget: "string" }
          - { label: "Percent4", name: "sofPercent4", widget: "number" }
      - label: "Experience"
        name: "experience"
        file: "content/Experience/Experience.md"
        fields:
          - { label: "Title1", name: "title1", widget: "string" }
          - { label: "Description1", name: "description1", widget: "text" }
          - { label: "Date1", name: "date1", widget: "text" }
          - { label: "Content1", name: "content1", widget: "text" }

          - { label: "Title2", name: "title2", widget: "string" }
          - { label: "Description2", name: "description2", widget: "text" }
          - { label: "Date2", name: "date2", widget: "text" }
          - { label: "Content2", name: "content2", widget: "text" }

          - { label: "Title3", name: "title3", widget: "string" }
          - { label: "Description3", name: "description3", widget: "text" }
          - { label: "Date3", name: "date3", widget: "text" }
          - { label: "Content3", name: "content3", widget: "text" }

          - { label: "Title4", name: "title4", widget: "string" }
          - { label: "Description4", name: "description4", widget: "text" }
          - { label: "Date4", name: "date4", widget: "text" }
          - { label: "Content4", name: "content4", widget: "text" }
