backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Card"
        name: "card"
        file: "content/Card/Card.md"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - label: "Featured Image"
            name: "thumbnail"
            widget: "image"
          - label: "Featured Image"
            name: "background"
            widget: "image"
      - label: "Description"
        name: "description"
        file: "content/Description/Description.md"
        fields:
          - { label: "Description", name: "description", widget: "text" }
      - label: "Education"
        name: "education"
        file: "content/Education/Education.md"
        fields:
          - { label: "Title1", name: "title1", widget: "string" }
          - { label: "Description1", name: "description1", widget: "text" }
          - { label: "Date1", name: "date1", widget: "text" }
          - { label: "Content1", name: "content1", widget: "text" }

          - { label: "Title2", name: "title2", widget: "string" }
          - { label: "Description2", name: "description2", widget: "text" }
          - { label: "Date2", name: "date2", widget: "text" }
          - { label: "Content2", name: "content2", widget: "text" }

          - { label: "Title3", name: "title3", widget: "string" }
          - { label: "Description3", name: "description3", widget: "text" }
          - { label: "Date3", name: "date3", widget: "text" }
          - { label: "Content3", name: "content3", widget: "text" }

          - { label: "Title4", name: "title4", widget: "string" }
          - { label: "Description4", name: "description4", widget: "text" }
          - { label: "Date4", name: "date4", widget: "text" }
          - { label: "Content4", name: "content4", widget: "text" }

          - { label: "Title5", name: "title5", widget: "string" }
          - { label: "Description5", name: "description5", widget: "text" }
          - { label: "Date5", name: "date5", widget: "text" }
          - { label: "Content5", name: "content5", widget: "text" }

          - { label: "Title6", name: "title6", widget: "string" }
          - { label: "Description6", name: "description6", widget: "text" }
          - { label: "Date6", name: "date6", widget: "text" }
          - { label: "Content6", name: "content6", widget: "text" }
      - label: skills
        name: skills
        file: "content/Skills/Skills.md"
        fields:
          - { label: "FirstSkill", name: "professional", widget: "string" }
          - { label: "language1", name: "pro1", widget: "string" }
          - { label: "Percent1", name: "proPercent1", widget: "number" }
          - { label: "language2", name: "pro2", widget: "string" }
          - { label: "Percent2", name: "proPercent2", widget: "number" }
          - { label: "language3", name: "pro3", widget: "string" }
          - { label: "Percent3", name: "proPercent3", widget: "number" }
          - { label: "language4", name: "pro4", widget: "string" }
          - { label: "Percent4", name: "proPercent4", widget: "number" }

          - { label: "SecondSkill", name: "personal", widget: "string" }
          - { label: "language1", name: "per1", widget: "string" }
          - { label: "Percent1", name: "perPercent1", widget: "number" }
          - { label: "language2", name: "per2", widget: "string" }
          - { label: "Percent2", name: "perPercent2", widget: "number" }
          - { label: "language3", name: "per3", widget: "string" }
          - { label: "Percent3", name: "perPercent3", widget: "number" }
          - { label: "language4", name: "per4", widget: "string" }
          - { label: "Percent4", name: "perPercent4", widget: "number" }

          - { label: "ThirdSkill", name: "software", widget: "string" }
          - { label: "language1", name: "sof1", widget: "string" }
          - { label: "Percent1", name: "sofPercent1", widget: "number" }
          - { label: "language2", name: "sof2", widget: "string" }
          - { label: "Percent2", name: "sofPercent2", widget: "number" }
          - { label: "language3", name: "sof3", widget: "string" }
          - { label: "Percent3", name: "sofPercent3", widget: "number" }
          - { label: "language4", name: "sof4", widget: "string" }
          - { label: "Percent4", name: "sofPercent4", widget: "number" }
      - label: "Experience"
        name: "experience"
        file: "content/Experience/Experience.md"
        fields:
          - { label: "Title1", name: "title1", widget: "string" }
          - { label: "Description1", name: "description1", widget: "text" }
          - { label: "Date1", name: "date1", widget: "text" }
          - { label: "Content1", name: "content1", widget: "text" }

          - { label: "Title2", name: "title2", widget: "string" }
          - { label: "Description2", name: "description2", widget: "text" }
          - { label: "Date2", name: "date2", widget: "text" }
          - { label: "Content2", name: "content2", widget: "text" }

          - { label: "Title3", name: "title3", widget: "string" }
          - { label: "Description3", name: "description3", widget: "text" }
          - { label: "Date3", name: "date3", widget: "text" }
          - { label: "Content3", name: "content3", widget: "text" }

          - { label: "Title4", name: "title4", widget: "string" }
          - { label: "Description4", name: "description4", widget: "text" }
          - { label: "Date4", name: "date4", widget: "text" }
          - { label: "Content4", name: "content4", widget: "text" }

      - label: "Pricing"
        name: "pricing"
        file: "content/Pricing/Pricing.md"
        fields:
          - { label: "Price1", name: "price1", widget: "number" }
          - { label: "Level1", name: "level1", widget: "text" }
          - { label: "brandWidth1", name: "brandWidth1", widget: "text" }
          - { label: "diskSpace1", name: "diskSpace1", widget: "text" }
          - { label: "databases1", name: "databases1", widget: "number" }
          - { label: "domain1", name: "domain1", widget: "text" }
          - { label: "subdomain1", name: "a", widget: "text" }

          - { label: "Price2", name: "price2", widget: "number" }
          - { label: "Level2", name: "level2", widget: "text" }
          - { label: "brandWidth2", name: "brandWidth2", widget: "text" }
          - { label: "diskSpace2", name: "diskSpace2", widget: "text" }
          - { label: "databases2", name: "databases2", widget: "number" }
          - { label: "domain2", name: "domain2", widget: "text" }
          - { label: "subdomain2", name: "subdomain2", widget: "text" }

          - { label: "Price3", name: "price3", widget: "number" }
          - { label: "Level3", name: "level3", widget: "text" }
          - { label: "brandWidth3", name: "brandWidth3", widget: "text" }
          - { label: "diskSpace3", name: "diskSpace3", widget: "text" }
          - { label: "databases3", name: "databases3", widget: "number" }
          - { label: "domain3", name: "domain3", widget: "text" }
          - { label: "subdomain3", name: "subdomain3", widget: "text" }
      - label: "Testimonial"
        name: "testimonial"
        file: "content/Testimonial/Testimonial.md"
        fields:
          - label: "Avatar Image 1"
            name: "avatar1"
            widget: "image"
          - { label: "Description 1", name: "description1", widget: "text" }
          - { label: "Author 1", name: "author1", widget: "text" }

          - label: "Avatar Image 2"
            name: "avatar2"
            widget: "image"
          - { label: "Description 2", name: "description2", widget: "text" }
          - { label: "Author 2", name: "author2", widget: "text" }

          - label: "Avatar Image 3"
            name: "avatar3"
            widget: "image"
          - { label: "Description 3", name: "description3", widget: "text" }
          - { label: "Author 3", name: "author3", widget: "text" }

          - label: "Logo 1"
            name: "logo1"
            widget: "image"
          - label: "Logo 2"
            name: "logo2"
            widget: "image"
          - label: "Logo 3"
            name: "logo3"
            widget: "image"
          - label: "Logo 4"
            name: "logo4"
            widget: "image"
          - label: "Logo 5"
            name: "logo5"
            widget: "image"
          - label: "Logo 6"
            name: "logo6"
            widget: "image"
          - label: "Logo 7"
            name: "logo7"
            widget: "image"
          - label: "Logo 8"
            name: "logo8"
            widget: "image"
          - label: "Logo 9"
            name: "logo9"
            widget: "image"
      - label: "Blog"
        name: "blog"
        file: "content/Blog/Blog.md"
        fields:
          - label: "Blog Image 1"
            name: "blogImg1"
            widget: "image"
          - { label: "fieldWork 1", name: "text1", widget: "string" }
          - { label: "JobName 1", name: "jobName1", widget: "string" }
          - { label: "Work 1", name: "work1", widget: "string" }
          - { label: "Work Title 1", name: "workTitle1", widget: "string" }
          - { label: "Description 1", name: "description1", widget: "text" }

          - label: "Blog Image 2"
            name: "blogImg2"
            widget: "image"
          - { label: "fieldWork 2", name: "text2", widget: "string" }
          - { label: "JobName 2", name: "jobName2", widget: "string" }
          - { label: "Work 2", name: "work2", widget: "string" }
          - { label: "Work Title 2", name: "workTitle2", widget: "string" }
          - { label: "Description 2", name: "description2", widget: "text" }

          - label: "Blog Image 3"
            name: "blogImg3"
            widget: "image"
          - { label: "fieldWork 3", name: "text3", widget: "string" }
          - { label: "JobName 3", name: "jobName3", widget: "string" }
          - { label: "Work 3", name: "work3", widget: "string" }
          - { label: "Work Title 3", name: "workTitle3", widget: "string" }
          - { label: "Description 3", name: "description3", widget: "text" }
      - label: "Logo Tab"
        name: "logoTab"
        file: "content/LogoTab/LogoTab.md"
        fields:
          - label: "LogoTab Image 1"
            name: "logoTabImg1"
            widget: "image"
          - label: "LogoTab Image 2"
            name: "logoTabImg2"
            widget: "image"
          - label: "LogoTab Image 3"
            name: "logoTabImg3"
            widget: "image"

      - label: "Dribble Tab"
        name: "DribbleTab"
        file: "content/DribbleTab/DribbleTab.md"
        fields:
          - label: "Dribble Image 1"
            name: "dribbleTabImg1"
            widget: "image"
          - label: "DribbleTab Image 2"
            name: "dribbleTabImg2"
            widget: "image"
          - label: "Dribble Image 3"
            name: "dribbleTabImg3"
            widget: "image"

      - label: "Website Tab"
        name: "WebsiteTab"
        file: "content/WebsiteTab/WebsiteTab.md"
        fields:
          - label: "Website Image 1"
            name: "WebsiteTabImg1"
            widget: "image"
          - label: "WebsiteTab Image 2"
            name: "WebsiteTabImg2"
            widget: "image"
          - label: "Website Image 3"
            name: "WebsiteTabImg3"
            widget: "image"
          - label: "Website Image 4"
            name: "WebsiteTabImg4"
            widget: "image"
          - label: "Website Image 5"
            name: "WebsiteTabImg5"
            widget: "image"
          - label: "Website Image 6"
            name: "WebsiteTabImg6"
            widget: "image"

      - label: "All Tab"
        name: "allTab"
        file: "content/AllTab/AllTab.md"
        fields:
          - label: "AllTab Image 1"
            name: "allTabImg1"
            widget: "image"
          - label: "AllTab Image 2"
            name: "allTabImg2"
            widget: "image"
          - label: "All Image 3"
            name: "allTabImg3"
            widget: "image"
          - label: "All Image 4"
            name: "allTabImg4"
            widget: "image"
          - label: "All Image 5"
            name: "allTabImg5"
            widget: "image"
          - label: "All Image 6"
            name: "allTabImg6"
            widget: "image"
          - label: "AllTab Image 7"
            name: "allTabImg7"
            widget: "image"
          - label: "AllTab Image 8"
            name: "allTabImg8"
            widget: "image"
          - label: "All Image 9"
            name: "allTabImg9"
            widget: "image"
          - label: "All Image 10"
            name: "allTabImg10"
            widget: "image"
          - label: "All Image 11"
            name: "allTabImg11"
            widget: "image"
          - label: "All Image 12"
            name: "allTabImg12"
            widget: "image"
      - label: "More Info Education"
        name: "moreInfo"
        file: "content/MoreInfo/MoreInfo.md"
        fields:
          - label: "MoreInfo Image"
            name: "infoImg"
            widget: "image"
          - { label: "MoreInfo Description", name: "desc", widget: "text" }
