backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/Home.md"
        fields:
          - label: "Card"
            name: "card"
            widget: "object"
            collapsed: true
            fields:
              - label: "Your Name"
                name: "yourName"
                widget: "string"

              - label: "Your Job"
                name: "yourJob"
                widget: "string"

              - label: "Avatar"
                name: "avtCard"
                widget: "image"
          - label: "Banner"
            name: "banner"
            widget: "object"
            collapsed: true
            fields:
              - label: "Avatar Menu"
                name: "avatar"
                widget: "image"

              - label: "Header Background"
                name: "bg"
                widget: "image"

          - label: "Blog"
            name: "blog"
            widget: "object"
            collapsed: true
            fields:
              - label: "Blog Item 1"
                name: "blogItem1"
                widget: "object"
                collapsed: true
                fields:
                  - label: "Blog Image"
                    name: "blogImg"
                    widget: "image"

                  - label: "field Work"
                    name: "fieldWork"
                    widget: "text"

                  - label: "Job Name"
                    name: "jobName"
                    widget: "string"

                  - label: "Work"
                    name: "work"
                    widget: "string"

                  - label: "Work Title"
                    name: "workTitle"
                    widget: "string"

                  - label: "Description"
                    name: "desc"
                    widget: "text"

              - label: "Blog Item 2"
                name: "blogItem2"
                widget: "object"
                collapsed: true
                fields:
                  - label: "Blog Image"
                    name: "blogImg"
                    widget: "image"

                  - label: "field Work"
                    name: "fieldWork"
                    widget: "text"

                  - label: "Job Name"
                    name: "jobName"
                    widget: "string"

                  - label: "Work"
                    name: "work"
                    widget: "string"

                  - label: "Work Title"
                    name: "workTitle"
                    widget: "string"

                  - label: "Description"
                    name: "desc"
                    widget: "text"

              - label: "Blog Item 3"
                name: "blogItem3"
                widget: "object"
                collapsed: true
                fields:
                  - label: "Blog Image"
                    name: "blogImg"
                    widget: "image"

                  - label: "field Work"
                    name: "fieldWork"
                    widget: "text"

                  - label: "Job Name"
                    name: "jobName"
                    widget: "string"

                  - label: "Work"
                    name: "work"
                    widget: "string"

                  - label: "Work Title"
                    name: "workTitle"
                    widget: "string"

                  - label: "Description"
                    name: "desc"
                    widget: "text"
